### ISSUE TITLE
 The size of tensor a (13) must match the size of tensor b (15) at non-singleton dimension 1

### ISSUE THREAD

**Issue by 123eye** [Phoenix-Shen/DSEN2_CR_PYTORCH#6]
in_ch= 15#输入通道数
out_ch = 13#输出通道数
作者您好，我在运行train.py的时候出现了这个问题，然后我发现是在config.py中的通道数是不匹配的，不知道这个是怎么解决的，直接修改通道数吗还是有别的方式

**Comment by Phoenix-Shen** [comment]
> in_ch= 15#输入通道数 out_ch = 13#输出通道数 作者您好，我在运行train.py的时候出现了这个问题，然后我发现是在config.py中的通道数是不匹配的，不知道这个是怎么解决的，直接修改通道数吗还是有别的方式

嗯，是这样的，可以灵活改变config.py中的参数以应对您的情况。在印象中论文原文中输入通道应该是15。

**Comment by 123eye** [comment]
是的，输入通道是15没错，当我改变输出通道为15时还是报一样的错误
cloud_img.shape torch.Size([1, 15, 256, 256])
ground_truth.shape torch.Size([1, 15, 256, 256])
csm_img.shape torch.Size([1, 1, 256, 256])
开始训练...
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    train(myconfig)
  File "train.py", line 102, in train
    img_fake = net(img_cld)
  File "/root/miniconda3/envs/dsen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/dsen2_cr/models/DSen2_CR.py", line 46, in forward
    return x[:,2:,:,:]+self.net(x)
RuntimeError: The size of tensor a (13) must match the size of tensor b (15) at non-singleton dimension 1

**Comment by 123eye** [comment]
x.shape torch.Size([1, 15, 256, 256])
self.net(x) torch.Size([1, 15, 256, 256])
x[:,2:,:,:] torch.Size([1, 13, 256, 256])
是的我输出来self.net(x)的输出是13通道，这个要怎么改

**Comment by Phoenix-Shen** [comment]
> x.shape torch.Size([1, 15, 256, 256]) self.net(x) torch.Size([1, 15, 256, 256]) x[:,2:,:,:] torch.Size([1, 13, 256, 256]) 是的我输出来self.net(x)的输出是13通道，这个要怎么改

在`config.py`的第34行，`out_ch = 13#输出通道数`，这个out_ch应该是13的，你看看是不是误修改成15了。

**Comment by 123eye** [comment]
是的 我只修改这一个地方，改成13也是报一样的错误

**Comment by 123eye** [comment]
这就又回到了最初的问题
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train(myconfig)
  File "train.py", line 100, in train
    loss= CARL_Loss(img_truth,img_csm,img_fake,img_cld)
  File "/root/autodl-tmp/dsen2_cr/utils/img_operations.py", line 65, in carl_error
    cscmae = t.mean(clearmask * t.abs(predicted - input_cloudy) + csm * t.abs(
RuntimeError: The size of tensor a (13) must match the size of tensor b (15) at non-singleton dimension 1

**Comment by Phoenix-Shen** [comment]
> 这就又回到了最初的问题 Traceback (most recent call last): File "train.py", line 131, in train(myconfig) File "train.py", line 100, in train loss= CARL_Loss(img_truth,img_csm,img_fake,img_cld) File "/root/autodl-tmp/dsen2_cr/utils/img_operations.py", line 65, in carl_error cscmae = t.mean(clearmask * t.abs(predicted - input_cloudy) + csm * t.abs( RuntimeError: The size of tensor a (13) must match the size of tensor b (15) at non-singleton dimension 1

这个问题有人已经提出来了，很奇怪，在我之前用的时候并没有出问题，有可能是我上传了之前的版本到github

https://github.com/Phoenix-Shen/DSEN2_CR_PYTORCH/issues/5

**Comment by 123eye** [comment]
loss= CARL_Loss(img_truth,img_csm,img_fake,img_cld)我在这个函数之前将img_cld拆分了一下，是对的吗

**Comment by Phoenix-Shen** [comment]
> loss= CARL_Loss(img_truth,img_csm,img_fake,img_cld)我在这个函数之前将img_cld拆分了一下，是对的吗

嗯，是对的。这几天比较忙回复不及时，不好意思哈。我目前没有条件运行代码，有任何问题欢迎在下面留言

**Comment by duang-sdau** [comment]
> > loss= CARL_Loss(img_truth,img_csm,img_fake,img_cld)我在这个函数之前将img_cld拆分了一下，是对的吗
> 
> 嗯，是对的。这几天比较忙回复不及时，不好意思哈。我目前没有条件运行代码，有任何问题欢迎在下面留言

您好，我想请问一下拆分img_cld是取前13个通道骂

**Comment by Phoenix-Shen** [comment]
> > > loss= CARL_Loss(img_truth,img_csm,img_fake,img_cld)我在这个函数之前将img_cld拆分了一下，是对的吗
> > 
> > 
> > 嗯，是对的。这几天比较忙回复不及时，不好意思哈。我目前没有条件运行代码，有任何问题欢迎在下面留言
> 
> 您好，我想请问一下拆分img_cld是取前13个通道骂

对的，是前13个通道，还有什么代码方面的问题可以随时在下面留言。也可以看看别人提的issues，里面有一些关于我代码的错误。

**Comment by duang-sdau** [comment]
![iteration_1](https://github.com/user-attachments/assets/7486a90a-ec37-4b0e-83c6-42b9b666b682)
您好，麻烦再请问一下您，为什么我输出图像的除云遮档部分之外的色彩与输入图像相差很大，我该怎么调整

**Comment by Phoenix-Shen** [comment]
> ![iteration_1](https://private-user-images.githubusercontent.com/174309773/397652692-7486a90a-ec37-4b0e-83c6-42b9b666b682.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODU4MTMsIm5iZiI6MTczNDY4NTUxMywicGF0aCI6Ii8xNzQzMDk3NzMvMzk3NjUyNjkyLTc0ODZhOTBhLWVjMzctNGIwZS04M2M2LTQyYjliNjY2YjY4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTdhYTBlNWQyMmVjNjdhMDY5ZGM2YjJkMTQzZmY5OGRiNTQzNThjYjYxMjA0ODMwZGY4MmJlMGVlZDg3NmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ftBwOZU1-eOrFCrRy8sjulcGaTvAw96Fc_Jj9hKi048) 您好，麻烦再请问一下您，为什么我输出图像的除云遮档部分之外的色彩与输入图像相差很大，我该怎么调整



> ![iteration_1](https://private-user-images.githubusercontent.com/174309773/397652692-7486a90a-ec37-4b0e-83c6-42b9b666b682.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODY2NTksIm5iZiI6MTczNDY4NjM1OSwicGF0aCI6Ii8xNzQzMDk3NzMvMzk3NjUyNjkyLTc0ODZhOTBhLWVjMzctNGIwZS04M2M2LTQyYjliNjY2YjY4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTE5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTkwY2Y0NWViNTIwOTYxNWRhNjIzYjA5M2I5NWUyNjZhM2EzZDdmMzY5YjA3ZDJiY2MyNDkzNWU4OTAzM2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iN35WoZioelnuoIWqlSnXw4IazXI7IuHS8DqRwS4wPg) 您好，麻烦再请问一下您，为什么我输出图像的除云遮档部分之外的色彩与输入图像相差很大，我该怎么调整

我看你这是Iteration 1的结果，一般要迭代个十几轮才能得到不错的结果，由于整个数据集太大了，建议使用1000张或者500张图片试一试。以下是具体方案：
1. 使用`torch.utils.data.Dataset`里头的Subset类随机分少量样本出来，作为训练集和测试集。
2. 我记得我当时大致使用这些参数就得到了不错的结果
  ```python
  batch_size=16 or 32
  epochs=100,
  lr=1e-4, 1e-5,,
  ```
3. 将training_loss和test_loss可视化，我记得代码里头有TensorBoard，看看Loss曲线有啥问题，是不是不收敛。如果不收敛，得检查输入输出，loss_function和网络结构。
4. 如果还是无法定位问题，可以贴上你的更多细节我们再讨论一下。

**Comment by duang-sdau** [comment]
> > ![iteration_1](https://private-user-images.githubusercontent.com/174309773/397652692-7486a90a-ec37-4b0e-83c6-42b9b666b682.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODU4MTMsIm5iZiI6MTczNDY4NTUxMywicGF0aCI6Ii8xNzQzMDk3NzMvMzk3NjUyNjkyLTc0ODZhOTBhLWVjMzctNGIwZS04M2M2LTQyYjliNjY2YjY4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTdhYTBlNWQyMmVjNjdhMDY5ZGM2YjJkMTQzZmY5OGRiNTQzNThjYjYxMjA0ODMwZGY4MmJlMGVlZDg3NmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ftBwOZU1-eOrFCrRy8sjulcGaTvAw96Fc_Jj9hKi048)您好，麻烦再请问一下您，为什么我输出图像的除云遮档部分之外的色彩与输入图像相差很大，我该怎么调整
> 
> > ![iteration_1](https://private-user-images.githubusercontent.com/174309773/397652692-7486a90a-ec37-4b0e-83c6-42b9b666b682.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODY2NTksIm5iZiI6MTczNDY4NjM1OSwicGF0aCI6Ii8xNzQzMDk3NzMvMzk3NjUyNjkyLTc0ODZhOTBhLWVjMzctNGIwZS04M2M2LTQyYjliNjY2YjY4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTE5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTkwY2Y0NWViNTIwOTYxNWRhNjIzYjA5M2I5NWUyNjZhM2EzZDdmMzY5YjA3ZDJiY2MyNDkzNWU4OTAzM2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iN35WoZioelnuoIWqlSnXw4IazXI7IuHS8DqRwS4wPg)您好，麻烦再请问一下您，为什么我输出图像的除云遮档部分之外的色彩与输入图像相差很大，我该怎么调整
> 
> 我看你这是Iteration 1的结果，一般要迭代个十几轮才能得到不错的结果，由于整个数据集太大了，建议使用1000张或者500张图片试一试。以下是具体方案：
> 
> 1. 使用里头的Subset类随机分少量样本出来，作为训练集和测试集。`torch.utils.data.Dataset`
> 2. 我记得我当时大致使用这些参数就得到了不错的结果
> 
> ```python
> batch_size=16 or 32
> epochs=100,
> lr=1e-4, 1e-5,,
> ```
> 
> 3. 将training_loss和test_loss可视化，我记得代码里头有TensorBoard，看看Losscurve有啥问题，是不是不收敛。如果不收敛，得检查输入输出，loss_function和网络结构。
> 4. 如果还是无法定位问题，可以贴上你的更多细节我们再讨论一下。

非常感谢您的回复，我再尝试一下
